### PR TITLE
Fixing issues and doing some improvements

### PR DESCRIPTION
**Pull request by renatomefidf**
Fixing composer installation to the correct one;
Fixing issue #198 
Updating Libs and travis

### CODE REVIEW

**Comment by renatomefidf** [comment]
Fixing #104

**Comment by naxhh** [comment]
Hi! Thanks for the PR!

Would be amazing that you PR each unrelated fix in different PR's.

Anyway take that in mind for next contributions :)

I'll check it at home! thanks again

**Comment by renatomefidf** [comment]
You're right, I should separated the layout changes too, because it's quite different from the original, after I updated the frontend framework a lot of things has broken!
If it is not good let me know to revert those changes!

**Comment by naxhh** [comment]
If is not a big deal to split them in different PR's will be easier for me to test and check them :)

**Comment by renatomefidf** [comment]
@naxhh I'll not be able to do that for the next week, if you can check it this way would be better or else you can wait! I'm sorry for that!

**Comment by naxhh** [comment]
Hi! okay no problem. next time keep it in mind :dancers: 

I was moving to another house so I was a bit off. I'll review ASAP! Thanks!

**Comment by naxhh** [comment]
Thanks for this! I'll test it with the master release.

**Comment by naxhh** [comment]
I just saw that the menu is not displayed correctly :(

**Comment by renatomefidf** [comment]
Can you send me a screenshot?

**Comment by naxhh** [comment]
I've created an issue for it :) #203

**Pull request merged**
