### PR TITLE
Redis - New database support

### PR DESCRIPTION
**Pull request by fabiorphp**

### CODE REVIEW

**Comment by InFog** [comment]
:+1:

**Comment by rafaell-lycan** [comment]
(y)

**Comment by naxhh** [comment]
Let me this week-end to test it... testing is a bit slow :(

Also I need a lot of time to re-test all master.. since we are still deploying 1.0 branch
I'm waiting the deploy credentials but hope soon we can start moving forward master branch as always

**Comment by naxhh** [comment]
Ok! So I've some time to test it.

Two things I'm concerned about:

1. `$ service redis_<port> status`
Why we chosen this approach?
I would normally expect to be able to do `service redis status`
I think this can, and will, bring some confusion to the users.

2. Idempotence
If we provision a second time. It will mark all the steps as "ok" because the files in `/tmp` stop most of the commands to execute.

But I we provision again in a week/moth or whenever our `/tmp' folder is configured to remove temporal files we will find out that our role is executing 3 expensive tasks without need:
```
TASK: [redis | Download] ******************************************************
changed: [192.168.33.99]

TASK: [redis | Extract] *******************************************************
changed: [192.168.33.99]

TASK: [redis | Compile] *******************************************************
changed: [192.168.33.99]
```

Can we add here a step to check if redis is installed and make this steps depend on that?

**Comment by fabiorphp** [comment]
I will fix!

**Comment by InFog** [comment]
@fabiorphp Fix, the things, all, you should. -- Yoda

**Comment by fabiorphp** [comment]
Updated!

**Comment by naxhh** [comment]
Checking the code seems ok. I didn't had time to run it. I'll be out this week so if someone can run it and merge if everything is ok that would be nice.

**Comment by fabiorphp** [comment]
Thanks @naxhh

**Comment by naxhh** [comment]
Since no one offered to test it :P

I'll try to do it this week/week-end. sorry for the delay!

**Comment by fabiorphp** [comment]
amen!

**Pull request merged**
