### PR TITLE
Feature/roles from repos

### PR DESCRIPTION
**Pull request by naxhh**
So this is the current way we will clone roles from their repos.

As @debo pointed out in chats. We could add galaxy so it will be easier. But first I really want to deploy 0.7.3

I've pending to check the deploy script.. So it will update the dependencies. But since I'm the only one doing that. That could wait. But it will in 0.7.3 for sure.

Roles in repo take in a conceptual change. You don't test roles with phansible UI. If you want to test the role you do it in the repo of the role itself. In the UI you only test that phansible creates the correct var files and includes the role in the bundle.

With this conceptual change testing phansible UI will become a lot easier and testing roles can be automated without pains as we are currently doing.

### CODE REVIEW

**Comment by naxhh** [comment]
ping @phansible/core-dev @phansible/collaborators for feedback

**Comment by InFog** [comment]
We had something like this before and it really seems the right direction to go. I mean, it will for sure add some complexity in the whole setup, but, as @naxhh said, testing will get easier.

It will, of course, spread the efforts and make it a little bit harder for newcomers to understand the design and the several repos. I think it would be nice to disable wikis and whatever else we can in the roles' repos in order to concentrate the main efforts in the main repo.

On the good side we could have people responsible for given repos, what would facilitate the maintainers work ;)

**Comment by fabiorphp** [comment]
It's a good approach, testing will get easier, but I see some problems

1 - If I want create new role, I need wait to create a new repo for this role?
2 - What's the time to run the entire ansible playbook? Now we have git clone, that will be a little more slow.

I think this is more easy to maintain the project, but we need resolve this issues.

**Comment by naxhh** [comment]
@InFog true! I'll disable wikis and stuff... I totally forgot about that
About responsables per roles.. that will be nice. With some hope we will not need them too much.

But is good not be responsible of the entire codebase :)

@fabiorphp 

Point 1 has to faces. From outside phansible. It could seem a "major" drawback. But you always could create the repo in your account. Told us about it and migrate it to phansible..

For members of phansible. I could give create repos permission to all the core dev team. But the true is that I like the step when you come to gitter and say. Hey! I want to introduce this role. And we can discuss that...

You don't need the repo for actually writing the code but for publishing it...


Thanks for the feedback.

**Comment by mikeSimonson** [comment]
Seems like the right direction for me too.

**Comment by debo** [comment]
@naxhh for the deploy script I might help if needed. What deploy script are we talking about.

@InFog not only this way we can also depend on third party playbooks until we have our own if needed.

@fabiorphp what do you mean exactly with the time to run the entire playbook? Also you don't have to clone, you can let ansible deal with the dependencies as I did in role-composer for instance. I don't think that really add too much overhead.

**Comment by sndpl** [comment]
Looks good!

**Comment by naxhh** [comment]
@debo deploy script is this one: https://github.com/phansible/phansible/blob/master/ansible/deploy.yml
Adding repo clone is trivial but I didn't have the time to do it.

I'm basing on master should be always stable. And since I'm currently deploying by hand. Because automating testing was a big mess... that wouldn't be a problem for now.

**Comment by debo** [comment]
@naxhh wouldn't be capistrano a better tool for the job than ansible?

**Comment by naxhh** [comment]
Maybe. But deployment is not one of the things that annoys me right now

**Comment by debo** [comment]
It was just an idea indeed. We need to focus on the playbooks first indeed.

**Comment by naxhh** [comment]
If there is no more feedback I will merge this on friday.

I'll appreciate if some of you check the roles repos and help debo and me fixing the test for them

**Pull request merged**
