### PR TITLE
Search engine

### PR DESCRIPTION
**Pull request by fabiorphp**
Search engine feature
- Apache Solr with cloud mode (Zookeeper)
- Elastic Search

### CODE REVIEW

**Comment by naxhh** [comment]
You want to kill me :)

Check Travis btw.
I think we have a too much children's situation... I need to take some time and think how to solve that...

Regarding the PR. I also need some time to learn how this stuff work :P

**Comment by fabiorphp** [comment]
Done!

**Comment by naxhh** [comment]
Thanks for the migration to 0.7 :D

I had a pending task for that! I'll try to test this asap and include it in next release.

**Comment by fabiorphp** [comment]
OK!

**Pull request merged**
