### PR TITLE
Added nodejs and npm as systempackages

### PR DESCRIPTION
**Pull request by samvdb**
Since node and npm are used quite frequently i added them to the system packages.

### CODE REVIEW

**Comment by naxhh** [comment]
Fine for me until we do some UI for node (If we ever plan to add other languages)

**Comment by InFog** [comment]
Hmmmm.... Having it as mandatory doesn't seems like a good thing to me.

Maybe some checkboxes on UI?

**Comment by samvdb** [comment]
What do you mean by mandatory? This should only allow these values to be added in the select box (autocomplete function).

**Comment by naxhh** [comment]
I was checking how puPHPet manages this, as they are a lot o sys packages...

They simply allow any input without forcing to be in a list...

So maybe that is a good solution. Anyway, that is out of the scope of this PR :)

**Comment by samvdb** [comment]
That would indeed be a better solution! However the autocomplete is nice for common packages, but it should not restrict the input.

**Comment by InFog** [comment]
Oh, sorry, @samvdb, I got it wrong... My fault.

If it's only to appear in the autocompletion, ok :+1:

**Pull request merged**
