### PR TITLE
Customizing your bundle url fix

### PR DESCRIPTION
**Pull request by janimattiellonen**

### CODE REVIEW

**Comment by naxhh** [comment]
WOW! can you explain me all this commits you moved here?

**Comment by janimattiellonen** [comment]
Hmm, I just created a new PR with 1.0 as the target :).

I started by forking this project, then I created a new branch from the master branch. I then pushed my changes and created a PR. First PR was against master but I created a new one against 1.0.

**Comment by naxhh** [comment]
Oh! ok... I see.

1.0 is an "old" version. Since master is a WIP for implementing an external API.

You have moved all the commits from master to 1.0 ups...
I'll close this and I'll make the change myself :)
If you want to do it you just need to re-do the changes but starting from scratch using the 1.0 branch :)

**Comment by janimattiellonen** [comment]
Ah! Good to know. Is this information available somewhere? So that I and others new to this project know how to properly create PRs using correct branches.

**Comment by naxhh** [comment]
Yes! I thought of adding this info when I saw your PR :P

Feel free to add it, if not, I'll add it soon :)

In the docs contributing and also in the readme :)

I'm  squashing some old bugs so, when I've a bit more of time I'll add this.

Thanks for the feedback

**Pull request closed without merging**
