### PR TITLE
MySQL and MariaDB - Multiple users

### PR DESCRIPTION
**Pull request by fabiorphp**
* Changed the layout to support this new feature
* Transform values before generate variables
* Changed the initial values
* Ansible roles was changed to iterate into user items

related #108

### CODE REVIEW

**Comment by naxhh** [comment]
I'll hold this a bit. Because I'm trying to move roles outside this repo (in an easier way than what we had before).

And sync commits is a hell

**Comment by fabiorphp** [comment]
Fixed!!!

**Comment by naxhh** [comment]
For some reason build has been running for more than 24hrs in php 7 test 
https://travis-ci.org/phansible/phansible/builds/88916304

W T F

**Comment by naxhh** [comment]
Hi! Try to move the role changes to the role repo. So we can integrate the changes there and then add the ui changes!

**Comment by naxhh** [comment]
Ping

**Pull request closed without merging**
