### PR TITLE
Twitter in the website

### PR DESCRIPTION
**Pull request by fabiorphp**
* Added twitter widget into index template
* Changed javascript and css to use aside tag

issue #107

### CODE REVIEW

**Comment by InFog** [comment]
:+1:

**Comment by fabiorphp** [comment]
@erikaheidi I need of the twitter widget to change in this PR. Please create the widget using phansible twitter account.

**Comment by erikaheidi** [comment]
hey @fabiorphp ! I'm gonna share the twitter credentials with you guys, doing this now.

**Comment by erikaheidi** [comment]
sent! ;)

**Comment by fabiorphp** [comment]
Done!

**Comment by fabiorphp** [comment]
Someone out there?

**Comment by rafaell-lycan** [comment]
(Y)

**Comment by naxhh** [comment]
Hi!

Just checked this and when you get to the very bottom of the page it displays the box on top of the footer :(

Can we try to fix it?

twitter-box

**Comment by fabiorphp** [comment]
I will fix!

**Comment by naxhh** [comment]
any update here?

**Comment by fabiorphp** [comment]
Unfortunately I have not had time to fix it, please close this PR

**Pull request closed without merging**
